
###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"junnu",
    "username":"junnu123",
    "password": "junnu@456",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"junnu123",
    "password": "junnu@45"
}

 
###
 
POST  http://localhost:3000/add-address/
Content-Type: application/json

{
    "id":"1",
  "name": "gowthami",
  "mobilenumber": "9876543210",
  "village": "gutthivaripalli",
  "mandal": "Gorantla",
  "district": "sathya sai",
  "state": "Ap",
  "post": "Budili",
  "pincode": "515241"

}

###

GET http://localhost:3000/addresses/ 


###
PUT http://localhost:3000/address/addressId/
Content-Type: application/json
{
    "id":"1",
  "name": "gowthami",
  "mobilenumber": "9876543210",
  "village": "gutthivaripalli",
  "mandal": "Gorantla",
  "district": "sathya sai",
  "state": "Ap",
  "post": "Budili",
  "pincode": "515241"

}

###
DELETE http://localhost:3000/address/addressId/
Content-Type: application/json
{
   "id":"1",
  "name": "gowthami",
  "mobilenumber": "9876543210",
  "village": "gutthivaripalli",
  "mandal": "Gorantla",
  "district": "sathya sai",
  "state": "Ap",
  "post": "Budili",
  "pincode": "515241"

}


